obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.122,-0.229 ], [0.122, -0.229], [-0.122, 0.229], [0.122, 0.229] ]
#robot_radius: ir_of_robot
inflation_radius: 0.55
transform_tolerance: 10
meter_scoring: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic:
laser_scan, marking: true, clearing: true}

